window.ENTOMO_DATA = {
  morphology: {
    clypeus: {name:'Clípeo', region:'Cabeça', orders:['Coleoptera','Hemiptera','Diptera'], diagnosis:'Esclerito frontal que sustenta o labro; importante para delimitar margens cefálicas.'},
    labrum: {name:'Labro', region:'Cabeça', orders:['Coleoptera','Orthoptera','Lepidoptera'], diagnosis:'Lábio superior móvel associado à apreensão alimentar.'},
    mandibles: {name:'Mandíbulas', region:'Cabeça', orders:['Coleoptera','Orthoptera','Hymenoptera'], diagnosis:'Estruturas mastigadoras-chave para diferenciar aparelho bucal mandibulado.'},
    maxillae: {name:'Maxilas', region:'Cabeça', orders:['Coleoptera','Lepidoptera'], diagnosis:'Manipulação de alimento e palpos maxilares com valor diagnóstico.'},
    labium: {name:'Lábio', region:'Cabeça', orders:['Hemiptera','Diptera','Lepidoptera'], diagnosis:'Elemento ventral; no rostro hemíptero forma canal alimentar.'},
    antennae: {name:'Antena', region:'Cabeça', orders:['Diptera','Coleoptera','Hymenoptera'], diagnosis:'Tipos filiforme, clavada, geniculada e aristada são decisivos em chaves.'},
    compoundEyes: {name:'Olhos compostos', region:'Cabeça', orders:['Odonata','Diptera','Hemiptera'], diagnosis:'O tamanho relativo e posição auxiliam identificação de hábitos e grupos.'},
    ocelli: {name:'Ocelos', region:'Cabeça', orders:['Hymenoptera','Odonata'], diagnosis:'Fotorreceptores simples, úteis no diagnóstico de adultos alados.'},
    pronotum: {name:'Pronoto', region:'Tórax', orders:['Coleoptera','Orthoptera','Hemiptera'], diagnosis:'Desenvolvimento do pronoto diferencia famílias e estratégias defensivas.'},
    mesonotum: {name:'Mesonoto', region:'Tórax', orders:['Diptera','Hymenoptera'], diagnosis:'Segmento torácico associado ao primeiro par funcional de asas.'},
    metanotum: {name:'Metanoto', region:'Tórax', orders:['Diptera','Coleoptera'], diagnosis:'Em Diptera relaciona-se aos halteres; em outros grupos ao segundo par alar.'},
    coxa: {name:'Coxa', region:'Tórax', orders:['Orthoptera','Coleoptera'], diagnosis:'Articulação basal da perna, importante na mecânica locomotora.'},
    trochanter: {name:'Trocânter', region:'Tórax', orders:['Coleoptera','Hymenoptera'], diagnosis:'Segmento de transição com variações úteis em diagnóstico fino.'},
    femur: {name:'Fêmur', region:'Tórax', orders:['Orthoptera','Hemiptera'], diagnosis:'Hiperdesenvolvido em saltadores e predadores.'},
    tibia: {name:'Tíbia', region:'Tórax', orders:['Orthoptera','Coleoptera'], diagnosis:'Espinhos tibiais e dilatações diagnósticas em famílias.'},
    tarsus: {name:'Tarso', region:'Tórax', orders:['Coleoptera','Diptera','Hymenoptera'], diagnosis:'Número de tarsômeros é critério clássico de chave taxonômica.'},
    elytra: {name:'Élitros', region:'Asas', orders:['Coleoptera'], diagnosis:'Asas anteriores esclerosadas, caráter definidor de Coleoptera.'},
    hemelytra: {name:'Hemélitros', region:'Asas', orders:['Hemiptera'], diagnosis:'Base coriácea e ápice membranoso; assinatura diagnóstica de Heteroptera.'},
    membranousWing: {name:'Asa membranosa', region:'Asas', orders:['Lepidoptera','Hymenoptera','Odonata'], diagnosis:'Venação e escamas permitem separar ordens e famílias.'},
    halteres: {name:'Halteres', region:'Asas', orders:['Diptera'], diagnosis:'Segundo par alar reduzido com função giroscópica; sinapomorfia de Diptera.'}
  },
  orders: {
    Coleoptera:{metamorphosis:'Holometábola',mouthpart:'Mastigador',wings:'Élitros + asas membranosas',antenna:'Variável (frequente clavada/filiforme)',legType:'Cursorial/fossorial',diagnostic:'Élitros rígidos cobrindo abdome; larvas geralmente eruciformes/campodeiformes.',importance:'Inclui pragas de grãos, raízes e madeira; também predadores úteis.',families:['Curculionidae','Chrysomelidae','Scarabaeidae','Carabidae']},
    Lepidoptera:{metamorphosis:'Holometábola',mouthpart:'Sugador sifonador (adulto)',wings:'Asas com escamas',antenna:'Filiforme/pectinada/clavada',legType:'Ambulatório',diagnostic:'Escamas nas asas; larvas lagartas com falsas pernas.',importance:'Grandes desfolhadoras e broqueadoras de culturas.',families:['Noctuidae','Pyralidae','Geometridae','Tortricidae']},
    Diptera:{metamorphosis:'Holometábola',mouthpart:'Lambedor/picador-sugador',wings:'1 par de asas + halteres',antenna:'Aristada/plumosa',legType:'Ambulatório',diagnostic:'Apenas um par alar funcional; presença de halteres.',importance:'Pragas de frutos e vetores.',families:['Tephritidae','Muscidae','Culicidae']},
    Hemiptera:{metamorphosis:'Hemimetábola',mouthpart:'Picador-sugador',wings:'Hemélitros ou asas uniformes',antenna:'Filiforme',legType:'Variável',diagnostic:'Rostro articulado; sugam seiva e podem transmitir viroses.',importance:'Percevejos e pulgões de alta relevância agrícola.',families:['Pentatomidae','Aphididae','Cicadellidae','Reduviidae']},
    Hymenoptera:{metamorphosis:'Holometábola',mouthpart:'Mastigador ou mastigador-lambedor',wings:'2 pares membranosos com hamuli',antenna:'Geniculada/filiforme',legType:'Ambulatório',diagnostic:'Constrição entre tórax e abdome em muitos grupos; ovipositor desenvolvido.',importance:'Polinizadores e parasitoides fundamentais no MIP.',families:['Formicidae','Braconidae','Apidae','Ichneumonidae']},
    Orthoptera:{metamorphosis:'Hemimetábola',mouthpart:'Mastigador',wings:'Tégminas + asas posteriores',antenna:'Filiforme',legType:'Saltatória',diagnostic:'Pernas posteriores saltatórias; aparelho estridulatório frequente.',importance:'Gafanhotos e grilos causam desfolha intensa.',families:['Acrididae','Gryllidae']},
    Thysanoptera:{metamorphosis:'Intermediária (paurometábola modificada)',mouthpart:'Raspador-sugador',wings:'Estreitas franjadas',antenna:'Moniliforme',legType:'Ambulatório',diagnostic:'Insetos diminutos com asas franjadas.',importance:'Danos por raspagem e transmissão de tospovírus.',families:[]},
    Isoptera:{metamorphosis:'Hemimetábola',mouthpart:'Mastigador',wings:'2 pares similares em reprodutivos',antenna:'Moniliforme',legType:'Cursorial',diagnostic:'Eusocialidade, castas e consumo de celulose.',importance:'Ataque a madeira, mudas e estruturas.',families:[]},
    Odonata:{metamorphosis:'Hemimetábola',mouthpart:'Mastigador',wings:'2 pares membranosos alongados',antenna:'Setácea curta',legType:'Predatória',diagnostic:'Olhos grandes e asas com rica venação.',importance:'Predadores naturais de outros insetos.',families:[]}
  },
  families: {
    Curculionidae:{order:'Coleoptera',morphology:'Rostro alongado, antenas geniculadas com clava.',damage:'Perfuração de grãos, caules e frutos.',importance:'Pragas-chave em armazenagem e campo.',differential:'Difere de Chrysomelidae pelo rostro evidente.'},
    Chrysomelidae:{order:'Coleoptera',morphology:'Corpo oval, muitas espécies coloridas, tarsos pseudo-tetrâmeros.',damage:'Desfolha intensa.',importance:'Afeta hortaliças e culturas anuais.',differential:'Sem rostro alongado típico de curculionídeos.'},
    Scarabaeidae:{order:'Coleoptera',morphology:'Antena lamelada, corpo robusto.',damage:'Larvas rizófagas e adultos em folhas/frutos.',importance:'Corós com perdas em raízes.',differential:'Antenas lameladas distinguem de Carabidae.'},
    Carabidae:{order:'Coleoptera',morphology:'Predadores, pernas longas, mandíbula forte.',damage:'Geralmente benéficos; raramente dano direto.',importance:'Controle biológico natural.',differential:'Hábito predador e corpo achatado.'},
    Noctuidae:{order:'Lepidoptera',morphology:'Mariposas noturnas; larvas robustas.',damage:'Lagartas desfolhadoras e cortadeiras.',importance:'Pragas severas em grãos.',differential:'Comparada a Geometridae, possui mais falsas pernas.'},
    Pyralidae:{order:'Lepidoptera',morphology:'Palpos labiais evidentes; asas triangulares.',damage:'Brocas e traças de grãos.',importance:'Impacto em pós-colheita.',differential:'Aspecto de "focinho" pelos palpos.'},
    Geometridae:{order:'Lepidoptera',morphology:'Larvas mede-palmo com poucas falsas pernas.',damage:'Desfolha.',importance:'Ataques periódicos em frutíferas.',differential:'Locomoção típica em arco.'},
    Tortricidae:{order:'Lepidoptera',morphology:'Adultos pequenos, asas em teto.',damage:'Enrolamento de folhas e dano em frutos.',importance:'Pragas em fruticultura.',differential:'Comportamento de enrolar folhas.'},
    Pentatomidae:{order:'Hemiptera',morphology:'Corpo em escudo, glândulas odoríferas.',damage:'Sucção de grãos e vagens.',importance:'Alta perda qualitativa e quantitativa.',differential:'Formato pentagonal típico.'},
    Aphididae:{order:'Hemiptera',morphology:'Pequenos, com sifúnculos.',damage:'Sucção de seiva e transmissão viral.',importance:'Rápida multiplicação partenogenética.',differential:'Sifúnculos ausentes em Cicadellidae.'},
    Cicadellidae:{order:'Hemiptera',morphology:'Corpo em cunha, pernas saltatórias.',damage:'Sucção e vetor de fitopatógenos.',importance:'Importantes em culturas perenes.',differential:'Movimento lateral rápido e ausência de sifúnculos.'},
    Reduviidae:{order:'Hemiptera',morphology:'Rostro curto e forte; predadores.',damage:'Predação de insetos, alguns hematófagos.',importance:'Alguns úteis em controle biológico.',differential:'Cabeça alongada e hábito predador.'},
    Tephritidae:{order:'Diptera',morphology:'Moscas de frutos com asas desenhadas.',damage:'Larvas em polpa de frutos.',importance:'Barreiras quarentenárias.',differential:'Padrões alares diagnósticos.'},
    Muscidae:{order:'Diptera',morphology:'Moscas sinantrópicas, arista plumosa variável.',damage:'Contaminação e vetoração mecânica.',importance:'Impacto sanitário em agroindústria.',differential:'Morfologia torácica sem padrão tefritídeo.'},
    Culicidae:{order:'Diptera',morphology:'Pernas longas, probóscide alongada.',damage:'Hematofagia e transmissão de patógenos.',importance:'Saúde pública rural.',differential:'Escamas em asas e postura característica.'},
    Formicidae:{order:'Hymenoptera',morphology:'Cintura com 1-2 nós, castas.',damage:'Cortadeiras e proteção de homópteros.',importance:'Grandes perdas em silvicultura e pastagens.',differential:'Pecíolo nodiforme evidente.'},
    Braconidae:{order:'Hymenoptera',morphology:'Parasitoides pequenos com ovipositor.',damage:'Benéficos: parasitam lagartas.',importance:'Controle biológico aplicado.',differential:'Venação alar reduzida versus Ichneumonidae.'},
    Apidae:{order:'Hymenoptera',morphology:'Corpo piloso, corbícula em muitas espécies.',damage:'Sem dano direto; picadas ocasionais.',importance:'Polinização agrícola.',differential:'Pilosidade e estrutura coletora de pólen.'},
    Ichneumonidae:{order:'Hymenoptera',morphology:'Parasitoides com ovipositor longo.',damage:'Benéficos.',importance:'Regulação de pragas.',differential:'Venação alar mais complexa que Braconidae.'},
    Acrididae:{order:'Orthoptera',morphology:'Antenas curtas, pernas saltatórias.',damage:'Desfolha e consumo de plântulas.',importance:'Surtos de gafanhotos.',differential:'Difere de Gryllidae por antenas curtas.'},
    Gryllidae:{order:'Orthoptera',morphology:'Antenas longas, corpo escuro, estridulação.',damage:'Corte de plântulas e dano em mudas.',importance:'Problema em horticultura.',differential:'Antenas longas e hábito noturno.'}
  }
};
